# Biblioteka numpy

## Instalacja

In [ ]:
pip install numpy

In [1]:
import numpy as np
np.__version__

'1.19.5'

In [ ]:
help(np.array)

## Tablice jednowymiarowe

In [ ]:
x = np.array([1, 3])

In [ ]:
x

array([1, 3])

In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.shape

(2,)

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.3, 2.3, 1.4])
x

array([1.3, 2.3, 1.4])

## Tablice dwuwymiarowe

In [ ]:
x = np.array([[1, 2], [3, 4]])

In [ ]:
x

array([[1, 2],
       [3, 4]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

## Tablice trójwymiarowe

In [ ]:
x = np.array(
    [[[1, 2, 3],
      [4, 5, 6]],
     [[7, 8, 9],
      [10, 11, 12]]])

In [ ]:
x

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape

(2, 2, 3)

## Typy danych

In [ ]:
a = np.array([1, 2, 3])
a.dtype

dtype('int64')

In [ ]:
a = np.array([1.0, 2.3, 3.3])
a.dtype

dtype('float64')

In [ ]:
a = np.array([1, 2, 3], dtype='float')
a.dtype

dtype('float64')

In [ ]:
a = np.array([1.0, 2.3, 3.3], dtype='int')
a.dtype

dtype('int64')

In [ ]:
a

array([1, 2, 3])

In [ ]:
a = np.array([1.0, 2, 3.3], 'complex')
a.dtype

dtype('complex128')

In [ ]:
a = np.array([True, False])
a.dtype

dtype('bool')

In [ ]:
a = np.array([24, 12.1, False])
a.dtype

dtype('float64')

In [ ]:
a[2]

0.0

In [ ]:
a = np.array([24, 120, -280], dtype=np.int8)
a.dtype

dtype('int8')

In [ ]:
a[2]

-24

## Tworzenie tablic

In [ ]:
m = np.zeros(shape=(4, 10))
m

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
m = np.zeros(shape=(4, 10), dtype=int)
m

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [3]:
m = np.ones(shape=(5, 5))
m

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.full(shape=(3, 3), fill_value=5, dtype=int)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(start=3, stop=10)

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(start=0, stop=100, step=20)

array([ 0, 20, 40, 60, 80])

In [11]:
np.linspace(start=0, stop=1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [12]:
np.linspace(start=0, stop=1, num=3)

array([0. , 0.5, 1. ])

In [25]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [29]:
a.reshape((2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

## Operacje na tablicach

In [32]:
a = np.arange(start=0, stop=6)
b = np.arange(start=4, stop=10)

In [33]:
np.add(a, b)

array([ 4,  6,  8, 10, 12, 14])

In [35]:
np.subtract(a, b)

array([-4, -4, -4, -4, -4, -4])

In [36]:
np.divide(a, b)

array([0.        , 0.2       , 0.33333333, 0.42857143, 0.5       ,
       0.55555556])

In [37]:
a * 3

array([ 0,  3,  6,  9, 12, 15])

In [38]:
b ** 2

array([16, 25, 36, 49, 64, 81])

In [40]:
a + b*b

array([16, 26, 38, 52, 68, 86])

In [41]:
a = np.array([3, 1, 4, 2])
b = np.array([3, -1, 3, 3])

print(a)
print(b)

[3 1 4 2]
[ 3 -1  3  3]


## Generowanie liczb pseudolosowych

In [45]:
np.random.seed(0)

In [46]:
np.random.rand()

0.5488135039273248

In [51]:
np.random.randn(10)

array([ 1.17877957, -0.17992484, -1.07075262,  1.05445173, -0.40317695,
        1.22244507,  0.20827498,  0.97663904,  0.3563664 ,  0.70657317])

In [49]:
np.random.randn(10, 4)

array([[-0.22593966, -1.65457077, -0.63972264, -0.4794198 ],
       [ 0.3113635 , -0.77602047, -0.30736481, -0.36652394],
       [ 1.11971196, -0.45792242,  0.4253934 , -0.02797118],
       [ 1.47598983,  0.6467801 , -0.36433431, -0.67877739],
       [-0.35362786, -0.74074747, -0.67502183, -0.13278426],
       [ 0.61980106,  1.79116846,  0.17100044, -1.72567135],
       [ 0.16065854, -0.85898532, -0.20642094,  0.48842647],
       [-0.83833097,  0.38116374, -0.99090328,  1.01788005],
       [ 0.3415874 , -1.25088622,  0.92525075, -0.90478616],
       [ 1.84369153,  1.52550724, -1.44553558,  0.37716061]])

In [50]:
np.random.rand()

0.952749011516985

In [54]:
np.random.randn(10, 2, 3)

array([[[ 0.01050002,  1.78587049,  0.12691209],
        [ 0.40198936,  1.8831507 , -1.34775906]],

       [[-1.270485  ,  0.96939671, -1.17312341],
        [ 1.94362119, -0.41361898, -0.74745481]],

       [[ 1.92294203,  1.48051479,  1.86755896],
        [ 0.90604466, -0.86122569,  1.91006495]],

       [[-0.26800337,  0.8024564 ,  0.94725197],
        [-0.15501009,  0.61407937,  0.92220667]],

       [[ 0.37642553, -1.09940079,  0.29823817],
        [ 1.3263859 , -0.69456786, -0.14963454]],

       [[-0.43515355,  1.84926373,  0.67229476],
        [ 0.40746184, -0.76991607,  0.53924919]],

       [[-0.67433266,  0.03183056, -0.63584608],
        [ 0.67643329,  0.57659082, -0.20829876]],

       [[ 0.39600671, -1.09306151, -1.49125759],
        [ 0.4393917 ,  0.1666735 ,  0.63503144]],

       [[ 2.38314477,  0.94447949, -0.91282223],
        [ 1.11701629, -1.31590741, -0.4615846 ]],

       [[-0.06824161,  1.71334272, -0.74475482],
        [-0.82643854, -0.09845252, -0.66347829]]])

In [56]:
np.random.randint(low=10, high=101, size=(2, 2))

array([[93, 59],
       [51, 56]])

In [65]:
np.random.choice([5, 10, 14, 23])

10

In [63]:
np.random.choice(['Python', 'Java', 'Kotlin', 'C++', 'JavaScript', 'Swift'])

'Python'

In [66]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
np.random.shuffle(data)
data

array([4, 3, 8, 7, 2, 0, 6, 9, 1, 5])

## Funkcje w bibliotece NumPy