# Biblioteka numpy

## Instalacja

In [1]:
pip install numpy

In [1]:
import numpy as np
np.__version__

'1.19.5'

In [ ]:
help(np.array)

## Tablice jednowymiarowe

In [12]:
x = np.array([1, 3])

In [5]:
x

array([1, 3])

In [6]:
type(x)

numpy.ndarray

In [7]:
x.shape

(2,)

In [9]:
x.dtype

dtype('int64')

In [10]:
x = np.array([1.3, 2.3, 1.4])
x

array([1.3, 2.3, 1.4])

## Tablice dwuwymiarowe

In [19]:
x = np.array([[1, 2], [3, 4]])

In [21]:
x

array([[1, 2],
       [3, 4]])

In [23]:
x.ndim

2

In [25]:
x.shape

(2, 2)

In [27]:
x.dtype

dtype('int64')

In [36]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

## Tablice trójwymiarowe

In [41]:
x = np.array(
    [[[1, 2, 3],
      [4, 5, 6]],
     [[7, 8, 9],
      [10, 11, 12]]])

In [44]:
x

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
x.ndim

3

In [48]:
x.shape

(2, 2, 3)

## Typy danych

In [5]:
a = np.array([1, 2, 3])
a.dtype

dtype('int64')

In [7]:
a = np.array([1.0, 2.3, 3.3])
a.dtype

dtype('float64')

In [8]:
a = np.array([1, 2, 3], dtype='float')
a.dtype

dtype('float64')

In [9]:
a = np.array([1.0, 2.3, 3.3], dtype='int')
a.dtype

dtype('int64')

In [11]:
a

array([1, 2, 3])

In [13]:
a = np.array([1.0, 2, 3.3], 'complex')
a.dtype

dtype('complex128')

In [14]:
a = np.array([True, False])
a.dtype

dtype('bool')

In [16]:
a = np.array([24, 12.1, False])
a.dtype

dtype('float64')

In [17]:
a[2]

0.0

In [27]:
a = np.array([24, 120, -280], dtype=np.int8)
a.dtype

dtype('int8')

In [28]:
a[2]

-24

## Tworzenie tablic

In [2]:
m = np.zeros(shape=(4, 10))
m

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [3]:
m = np.zeros(shape=(4, 10), dtype=int)
m

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])